sudo: false
language: rust
rust:
- 1.22.0  # Two releases back
- stable
- beta
- nightly

matrix:
  include:
  - env: RUSTFMT
    rust: 1.31.0  # `stable`: Locking down for consistent behavior
    install:
      - rustup component add rustfmt
    script:
      - cargo fmt -- --check
  - env: RUSTFLAGS="-D warnings"
    rust: 1.31.0  # `stable`: Locking down for consistent behavior
    install:
    script:
    - cargo check --tests
  - env: CLIPPY
    rust: 1.31.0  # `stable`: Locking down for consistent behavior
    install:
      - rustup component add clippy
    script:
      - cargo clippy

install:
- rustc -Vv
- cargo -V

script:
- cargo check --verbose
- cargo test --verbose
- cargo run --verbose
- printenv

cache:
  cargo: true
