version: 2

jobs:
  build:
    docker:
      # The image used to build our project, build
      # your own using the Dockerfile provided below
      # and replace here. I put my own image here for
      # the example.
      - image: abronan/rust-circleci:latest

    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Versions
          command: |
            rustup run stable rustc --version --verbose
            rustup run stable cargo --version --verbose
      - run:
          name: Build
          command: rustup run stable cargo check --verbose
      - run:
          name: Test
          command: rustup run stable cargo test --verbose
      - run:
          name: Dump (baseline)
          command: printenv
      - run:
          name: Dump
          command: rustup run stable cargo run --verbose
      - save_cache:
          key: project-cache
          paths:
            - "~/.cargo"
            - "./target"

